### ISSUE TITLE
Day 2, checklist for Wednesday

### ISSUE THREAD

**Issue by eklemen** [jrutishauser/TIY-Mashup#8]
- [x] _Making Chrome extensions that make the world a better place_ S
- [x] Add CSS to make _something beautiful_ S
  - [x] Style buttons 
  - [ ] ~~Trello style layout/design~~
  - [x] PURPLE AND PINK!
  - [ ] Doritos and Dr.Pepper!!
  - [x] Link to Susannas Calendy page
  - [x] Change picture/icon? Avatar in the making

**Slack Stuff** L
- [x] Change user icon so its not a monkey emoji :monkey_face: 
- [ ] Possibly line break the answer so its not on the same line as the question
- [x] Dont forget to change the room its sending answers to as orl_jan2015_frontend
- [x] Accept user token to post to slack
- [ ] Login to slack and have token auto grabbed
#### BEAST MODE L
- [ ] Add a button to rsvp yourself for iron pints
  - [ ] Send the username to slack as a message alerting room who just RSVP'd
#### SUPER BEAST MODE XL
- [ ] Send this data to github and check off an Issue with users github names listed

**Comment by jrutishauser** [comment]
added the button to Susanna's calendly page.

**Comment by jrutishauser** [comment]
Trello theme looks boring, I went rogue!
